/* eslint-disable */
// @ts-nocheck
// Regenerated by TanStack Start during vite build. This placeholder exists so
// the module graph resolves before the plugin writes the real tree.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtelierHouseRouteImport } from './routes/atelier-house'
import { Route as AteliersRouteImport } from './routes/ateliers'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AteliersIndexRouteImport } from './routes/ateliers.index'
import { Route as AteliersSlugRouteImport } from './routes/ateliers.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ShowroomSlugRouteImport } from './routes/showroom.$slug'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioNewRouteImport } from './routes/studio.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AccountRoute = AccountRouteImport.update({ id: '/account', path: '/account', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AtelierHouseRoute = AtelierHouseRouteImport.update({ id: '/atelier-house', path: '/atelier-house', getParentRoute: () => rootRouteImport } as any)
const AteliersRoute = AteliersRouteImport.update({ id: '/ateliers', path: '/ateliers', getParentRoute: () => rootRouteImport } as any)
const BagRoute = BagRouteImport.update({ id: '/bag', path: '/bag', getParentRoute: () => rootRouteImport } as any)
const CheckoutRoute = CheckoutRouteImport.update({ id: '/checkout', path: '/checkout', getParentRoute: () => rootRouteImport } as any)
const JournalRoute = JournalRouteImport.update({ id: '/journal', path: '/journal', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const QuizRoute = QuizRouteImport.update({ id: '/quiz', path: '/quiz', getParentRoute: () => rootRouteImport } as any)
const ShopRoute = ShopRouteImport.update({ id: '/shop', path: '/shop', getParentRoute: () => rootRouteImport } as any)
const StudioRoute = StudioRouteImport.update({ id: '/studio', path: '/studio', getParentRoute: () => rootRouteImport } as any)
const TermsRoute = TermsRouteImport.update({ id: '/terms', path: '/terms', getParentRoute: () => rootRouteImport } as any)
const WelcomeRoute = WelcomeRouteImport.update({ id: '/welcome', path: '/welcome', getParentRoute: () => rootRouteImport } as any)
const AteliersIndexRoute = AteliersIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => AteliersRoute } as any)
const AteliersSlugRoute = AteliersSlugRouteImport.update({ id: '/$slug', path: '/$slug', getParentRoute: () => AteliersRoute } as any)
const JournalIndexRoute = JournalIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => JournalRoute } as any)
const JournalSlugRoute = JournalSlugRouteImport.update({ id: '/$slug', path: '/$slug', getParentRoute: () => JournalRoute } as any)
const SSlugRoute = SSlugRouteImport.update({ id: '/s/$slug', path: '/s/$slug', getParentRoute: () => rootRouteImport } as any)
const ShopIndexRoute = ShopIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => ShopRoute } as any)
const ShopSlugRoute = ShopSlugRouteImport.update({ id: '/$slug', path: '/$slug', getParentRoute: () => ShopRoute } as any)
const ShowroomSlugRoute = ShowroomSlugRouteImport.update({ id: '/showroom/$slug', path: '/showroom/$slug', getParentRoute: () => rootRouteImport } as any)
const StudioIndexRoute = StudioIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => StudioRoute } as any)
const StudioNewRoute = StudioNewRouteImport.update({ id: '/new', path: '/new', getParentRoute: () => StudioRoute } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({ id: '/api/auth/$', path: '/api/auth/$', getParentRoute: () => rootRouteImport } as any)

const AteliersRouteWithChildren = AteliersRoute._addFileChildren({ AteliersSlugRoute, AteliersIndexRoute })
const JournalRouteWithChildren = JournalRoute._addFileChildren({ JournalSlugRoute, JournalIndexRoute })
const ShopRouteWithChildren = ShopRoute._addFileChildren({ ShopSlugRoute, ShopIndexRoute })
const StudioRouteWithChildren = StudioRoute._addFileChildren({ StudioNewRoute, StudioIndexRoute })

export const routeTree = rootRouteImport._addFileChildren({
  IndexRoute,
  AccountRoute,
  AdminRoute,
  AtelierHouseRoute,
  AteliersRoute: AteliersRouteWithChildren,
  BagRoute,
  CheckoutRoute,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute,
  PrivacyRoute,
  QuizRoute,
  ShopRoute: ShopRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  TermsRoute,
  WelcomeRoute,
  SSlugRoute,
  ShowroomSlugRoute,
  ApiAuthSplatRoute,
})

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
