/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtelierHouseRouteImport } from './routes/atelier-house'
import { Route as AteliersRouteImport } from './routes/ateliers'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AteliersIndexRouteImport } from './routes/ateliers.index'
import { Route as AteliersSlugRouteImport } from './routes/ateliers.$slug'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskThreadIdRouteImport } from './routes/desk.$threadId'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ShowroomSlugRouteImport } from './routes/showroom.$slug'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioNewRouteImport } from './routes/studio.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierHouseRoute = AtelierHouseRouteImport.update({
  id: '/atelier-house',
  path: '/atelier-house',
  getParentRoute: () => rootRouteImport,
} as any)
const AteliersRoute = AteliersRouteImport.update({
  id: '/ateliers',
  path: '/ateliers',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AteliersIndexRoute = AteliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AteliersRoute,
} as any)
const AteliersSlugRoute = AteliersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AteliersRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskThreadIdRoute = DeskThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => DeskRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShowroomSlugRoute = ShowroomSlugRouteImport.update({
  id: '/showroom/$slug',
  path: '/showroom/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioNewRoute = StudioNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/atelier-house': typeof AtelierHouseRoute
  '/ateliers': typeof AteliersRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/desk': typeof DeskRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/shop': typeof ShopRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/ateliers/$slug': typeof AteliersSlugRoute
  '/desk/$threadId': typeof DeskThreadIdRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/studio/new': typeof StudioNewRoute
  '/ateliers/': typeof AteliersIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/atelier-house': typeof AtelierHouseRoute
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/ateliers/$slug': typeof AteliersSlugRoute
  '/desk/$threadId': typeof DeskThreadIdRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/studio/new': typeof StudioNewRoute
  '/ateliers': typeof AteliersIndexRoute
  '/desk': typeof DeskIndexRoute
  '/journal': typeof JournalIndexRoute
  '/shop': typeof ShopIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/atelier-house': typeof AtelierHouseRoute
  '/ateliers': typeof AteliersRouteWithChildren
  '/bag': typeof BagRoute
  '/checkout': typeof CheckoutRoute
  '/desk': typeof DeskRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/shop': typeof ShopRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/ateliers/$slug': typeof AteliersSlugRoute
  '/desk/$threadId': typeof DeskThreadIdRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/showroom/$slug': typeof ShowroomSlugRoute
  '/studio/new': typeof StudioNewRoute
  '/ateliers/': typeof AteliersIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/atelier-house'
    | '/ateliers'
    | '/bag'
    | '/checkout'
    | '/desk'
    | '/journal'
    | '/login'
    | '/privacy'
    | '/quiz'
    | '/shop'
    | '/studio'
    | '/terms'
    | '/welcome'
    | '/ateliers/$slug'
    | '/desk/$threadId'
    | '/journal/$slug'
    | '/s/$slug'
    | '/shop/$slug'
    | '/showroom/$slug'
    | '/studio/new'
    | '/ateliers/'
    | '/desk/'
    | '/journal/'
    | '/shop/'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/atelier-house'
    | '/bag'
    | '/checkout'
    | '/login'
    | '/privacy'
    | '/quiz'
    | '/terms'
    | '/welcome'
    | '/ateliers/$slug'
    | '/desk/$threadId'
    | '/journal/$slug'
    | '/s/$slug'
    | '/shop/$slug'
    | '/showroom/$slug'
    | '/studio/new'
    | '/ateliers'
    | '/desk'
    | '/journal'
    | '/shop'
    | '/studio'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/atelier-house'
    | '/ateliers'
    | '/bag'
    | '/checkout'
    | '/desk'
    | '/journal'
    | '/login'
    | '/privacy'
    | '/quiz'
    | '/shop'
    | '/studio'
    | '/terms'
    | '/welcome'
    | '/ateliers/$slug'
    | '/desk/$threadId'
    | '/journal/$slug'
    | '/s/$slug'
    | '/shop/$slug'
    | '/showroom/$slug'
    | '/studio/new'
    | '/ateliers/'
    | '/desk/'
    | '/journal/'
    | '/shop/'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AtelierHouseRoute: typeof AtelierHouseRoute
  AteliersRoute: typeof AteliersRouteWithChildren
  BagRoute: typeof BagRoute
  CheckoutRoute: typeof CheckoutRoute
  DeskRoute: typeof DeskRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  ShopRoute: typeof ShopRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  SSlugRoute: typeof SSlugRoute
  ShowroomSlugRoute: typeof ShowroomSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier-house': {
      id: '/atelier-house'
      path: '/atelier-house'
      fullPath: '/atelier-house'
      preLoaderRoute: typeof AtelierHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ateliers': {
      id: '/ateliers'
      path: '/ateliers'
      fullPath: '/ateliers'
      preLoaderRoute: typeof AteliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ateliers/': {
      id: '/ateliers/'
      path: '/'
      fullPath: '/ateliers/'
      preLoaderRoute: typeof AteliersIndexRouteImport
      parentRoute: typeof AteliersRoute
    }
    '/ateliers/$slug': {
      id: '/ateliers/$slug'
      path: '/$slug'
      fullPath: '/ateliers/$slug'
      preLoaderRoute: typeof AteliersSlugRouteImport
      parentRoute: typeof AteliersRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/$threadId': {
      id: '/desk/$threadId'
      path: '/$threadId'
      fullPath: '/desk/$threadId'
      preLoaderRoute: typeof DeskThreadIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/showroom/$slug': {
      id: '/showroom/$slug'
      path: '/showroom/$slug'
      fullPath: '/showroom/$slug'
      preLoaderRoute: typeof ShowroomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/new': {
      id: '/studio/new'
      path: '/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof StudioNewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AteliersRouteChildren {
  AteliersSlugRoute: typeof AteliersSlugRoute
  AteliersIndexRoute: typeof AteliersIndexRoute
}

const AteliersRouteChildren: AteliersRouteChildren = {
  AteliersSlugRoute: AteliersSlugRoute,
  AteliersIndexRoute: AteliersIndexRoute,
}

const AteliersRouteWithChildren = AteliersRoute._addFileChildren(
  AteliersRouteChildren,
)

interface DeskRouteChildren {
  DeskThreadIdRoute: typeof DeskThreadIdRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskThreadIdRoute: DeskThreadIdRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface StudioRouteChildren {
  StudioNewRoute: typeof StudioNewRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioNewRoute: StudioNewRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AtelierHouseRoute: AtelierHouseRoute,
  AteliersRoute: AteliersRouteWithChildren,
  BagRoute: BagRoute,
  CheckoutRoute: CheckoutRoute,
  DeskRoute: DeskRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  ShopRoute: ShopRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  SSlugRoute: SSlugRoute,
  ShowroomSlugRoute: ShowroomSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
